# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Hero
  description: Academic-style page hero with research focus and navigation
  icon: school
  tags:
    - Structure
    - Research
    - Robotics
    - Navigation

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  description_html: ""
  image: ""
  image_alt: ""
  cta_button: ""
  cta_button_link: ""
  works_button: ""
  works_button_link: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Hi there, I am Vimal
  description_html: >
    Robotics Engineer specializing in <strong>ROS-based autonomous systems</strong>,
    <strong>embedded robotics</strong>, and <strong>human-centric intelligent machines</strong>.
    My work spans mobile robotics, perception, control, and real-world deployment,
    with a focus on building reliable systems that bridge research and practice.
  image: /images/projects/stormbreaker/cover.jpg
  image_alt: Autonomous assistive robot prototype
  cta_button: View Timeline
  cta_button_link: "/timeline/"
  works_button: Selected Projects
  works_button_link: "/projects/"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
